fix pyyaml / yaml config load
building with the last version of pyyaml, exporter fails to start:

```
Traceback (most recent call last):
  File "/usr/src/app/openldap_exporter.py", line 148, in <module>
    config = yaml.load(arguments.config)
TypeError: load() missing 1 required positional argument: 'Loader'
```

see https://stackoverflow.com/a/69581453/5607207